### ISSUE TITLE
Corallus shots spawn as soon as he jumps.

### ISSUE THREAD

**Issue by Sagisolar** [Tslat/Advent-Of-Ascension#60] opened 2018-10-29 19:56 UTC
Tslat 1.1.3

I think they're ment to spawn when crash lands.

**Comment by Sagisolar** [comment] 2018-10-30 06:56
Im pretty sure that corrallus shots are ment spawn when corallus hits the ground when he makes the crater.

**Comment by Tslat** [comment] 2019-04-18 03:23
Duplicate of 564

**Closed by Tslat** 2019-04-18 03:23 UTC
Labels: duplicate, needs further info
