### ISSUE TITLE
Plants replace log blocks on trees

### ISSUE THREAD

**Issue by NeoVolt** [Tslat/Advent-Of-Ascension#1819] opened 2020-08-19 20:43 UTC
**Mod Version**
What version of the mod are you on?

3.3.4

**Describe the bug**

Trees often generate floating or partially destroyed due to plants generating where the log blocks should be

**To Reproduce**
Steps to reproduce the behaviour:
1. Launch the mod
2. Go to any dimension with trees and ground plants

**Expected behavior**

The plants should not override the log blocks

**Screenshots**

![image](https://user-images.githubusercontent.com/57927345/90687584-abfdca80-e232-11ea-8c73-ecc5aa32a0fb.png)

**Comment by EatingSilencer** [comment] 2020-08-20 15:02
This might be a duplicate of #1531.

**Closed** 2021-11-22 23:48 UTC
Labels: existing content change
