### ISSUE TITLE
ProjectE comptability

### ISSUE THREAD

**Issue by CCtuhulu** [Tslat/Advent-Of-Ascension#1429] opened 2020-04-23 10:41 UTC
Adding EMC values to all items and blocks (i don't know how to explain it better).

**Comment by matthiasrsl** [comment] 2020-05-20 15:29
You can do it yourself by setting EMC values to AoA items with the /projecte setemc command. The only difficulty is to find well-balanced EMC values.

**Comment by Tslat** [comment] 2020-05-30 03:20
Closing duplicate of #1519

**Closed by Tslat** 2020-05-30 03:20 UTC
Labels: Third Party Mod Compatibility, duplicate
