### ISSUE TITLE
Toy Towers not generating, or even not existing.

### ISSUE THREAD

**Issue by legitadimc** [Tslat/Advent-Of-Ascension#2452] opened 2021-04-03 11:19 UTC
**Mod Version**
3.5 beta 2

**Describe the bug**
Toy Towers probably don't exist.

**To Reproduce**
You can either try and find one in Celeve, use /locate to see it not being listed or using /aoa structures generate to see if it generates.

**Expected behavior**
They should exist.

**Comment by EatingSilencer** [comment] 2021-04-03 13:47
Duplicate of #2379

**Closed as completed** 2021-04-03 19:51 UTC
Labels: duplicate
