### ISSUE TITLE
Chainsaw should be a thing instead of unobtainable

### ISSUE THREAD

**Issue by Hamburger666** [Tslat/Advent-Of-Ascension#1840] opened 2020-08-31 07:27 UTC
**Describe the new feature you think would be good to add**
A specific and detailed description of what you want to see.
Make chainsaw a special award for achiving Logging lv.100

**Add any alternative implementations you think might work**
Is there a slightly different way you think might work as well?
put it into looging's loot table is also ok i think

**Include any additional background information**
Does this suggestion relate to anything existing? Has it been talked about previously?
i just like how it can shread leaves and logs so quickly, so i posted this

**Comment by Tslat** [comment] 2020-09-04 03:52
Duplicate of #1854

**Closed by Tslat** 2020-09-04 03:52 UTC
Labels: duplicate, existing content change
