### ISSUE TITLE
Dungeon Keeper has weird trade issue with Progress Token trade

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Advent-Of-Ascension#2071] opened 2020-11-29 20:08 UTC
**Mod Version**
What version of the mod are you on?
3.4-Beta-4

**Describe the bug**
When you trade for the Progress Token from the Dungeon Keeper over and over again, the X icon can appear as if the trade is locked, but the trade isn't actually locked and you can keep buying things as if it weren't locked.

**To Reproduce**
Steps to reproduce the behaviour:
1. Get a stack of silver coins.
2. Use the stack to buy as many progress tokens as possible.
3. See error

**Expected behavior**
The locking symbol never appears, as the trade should never be locked.

**Screenshots**
![image](https://user-images.githubusercontent.com/44556728/100552360-c8a79680-3254-11eb-801d-c9956e82f034.png)

**Comment by Tslat** [comment] 2020-11-29 20:29
Duplicate of the other npc trade bug

**Closed as completed** 2020-11-30 06:27 UTC
Labels: bug
