### ISSUE TITLE
AoA is not compatible with EvilCraft

### ISSUE THREAD

**Issue by uhloin** [Tslat/Advent-Of-Ascension#4372] opened 2024-08-29 19:53 UTC
**Mod Version**
AoA3 1.20.1-3.7.1 (Beta)

**Describe the bug**
Cannot open EvilCraft in-game manual ("Origins of Darkness"). It just ignores right click. If remove AoA3, it opens again.

**Comment by Tslat** [comment] 2024-08-29 22:24
Have you reported this to evilcraft

**Comment by uhloin** [comment] 2024-08-30 10:16
Not yet, because I think bug in AoA has higher probability
1) It's not EvilCraft blocks functionality of AoA, but AoA blocks functionality of EvilCraft. 
2) I tried previous version EvilCraft to be sure this is not a new bug from new version of EvilCraft. 
3) EC is in stable release state, AoA is beta and unfinished and looks buggy .
4) For example, I have compatibility bug with Integration Dynamics: after game loading it cannot open remote crafter until I remove AoA. Also after game loading first opening of player inventory causes huge lag - also until I remove AoA.

**Comment by Tslat** [comment] 2024-08-30 10:27
> Also after game loading first opening of player inventory causes huge lag - also until I remove AoA.

this is normal vanilla behaviour - it's exacerbated by AoA having a lot of items. It is not a bug

> after game loading it cannot open remote crafter until I remove AoA

Has this been reported?

> It's not EvilCraft blocks functionality of AoA, but AoA blocks functionality of EvilCraft.

That's not at all how this works

Report it to evilcraft

Your description of AoA being unfinished and buggy is also not true, but it is a large mod that covers a lot of areas, so conflicts are inevitable

**Comment by uhloin** [comment] 2024-08-30 10:35
Of course, huge mod causes more bugs, it's absolutely normal situation. Currently, I prefer to temporary remove AoA and wait more or less stable release, may be those bugs disappeared. If not, then I'll report to EvilCraft and Integrated Dynamics.

**Comment by Tslat** [comment] 2024-08-30 20:51
I'll close this issue then since there's nothing that AoA does inherently that should cause this, and AoA is in a stable release

You can report it to evilcraft if you want

**Closed as not planned by Tslat** 2024-08-30 20:51 UTC
Labels: Third Party Mod Compatibility
