### ISSUE TITLE
Increase event frequency + add cooldown mechanic

### ISSUE THREAD

**Issue by maladaptly** [Tslat/Advent-Of-Ascension#726] opened 2019-06-15 08:13 UTC
**Describe/name the existing feature this suggestion relates to**
Event frequency/odds

**Describe the change or feature you think would be good to see**
It has been a solid ingame month since the last blood hunt on my server at this point, I think.

My suggestion is to add running counters of the number of days elapsed since the last time an event occurred (full moon excepted, for obvious reasons), and the odds of an event occurring are based on that counter. For example, an event could have a 1% chance of occurring the day/night after, and that chance increases by 0.25% every day until it does occur, at which point the chance resets to 1%.

Hopefully that'll give them a little consistency without making them predictable.

**Comment by Tslat** [comment] 2019-06-15 14:03
I was going to mark this as a duplicate of #724 but it's slightly different I guess.
Maybe take a look at that one and see if that suggestion is what you want instead. If so, close this suggestion.
If not, you can leave it open

**Closed** 2021-03-29 07:23 UTC
Labels: existing content change
