### ISSUE TITLE
Project e compat

### ISSUE THREAD

**Issue by NuggetKitten** [Tslat/Advent-Of-Ascension#1277] opened 2020-03-03 15:21 UTC
**Describe/name the existing feature this suggestion relates to**
Provide the specific, exact name if applicable, and a brief description as necessary.
I am a lazy dude. I don't wanna make emc  values . And I am bad at balancing
**Describe the change or feature you think would be good to see**
A specific and detailed description of what you want to see changed.
Add EMC values to some items.
**Add any alternative implementations you think might work**
Is there a slightly different way you think might work as well?
idk
**Include any additional background information**
Does this suggestion relate to any other suggestions or bugs? Has it been talked about previously?
compat update!

**Comment by Tslat** [comment] 2020-05-30 03:20
Closing duplicate of #1519

**Closed by Tslat** 2020-05-30 03:20 UTC
Labels: Third Party Mod Compatibility, duplicate
