### ISSUE TITLE
Wrong Unicode Characters in Advent GUI

### ISSUE THREAD

**Issue by masterbobli** [Tslat/Advent-Of-Ascension#709] opened 2019-06-01 06:32 UTC
**Mod Version**
3.1.2.b 

**Describe the bug**
Wrong Unicode characters are displayed in Advent GUI

**To Reproduce**
Steps to reproduce the behaviour:
1. Launch the game with aoa
2. Change the language into Chinese
3. Create a new world
4. Open the advent GUI
5. Incorrect Characters are shown

**Expected behavior**
Characters in the GUI should be the same as the the ones in the lang files.

**Screenshots**
![10ECF9C1-2075-4931-8A21-8D401A22B5C7](https://user-images.githubusercontent.com/37212918/58744786-e8040e80-8479-11e9-92cf-18c9ef1834b4.png)

**Comment by Tslat** [comment] 2019-06-01 08:27
I've been made aware of this and it's extremely bizarre... I don't pick the characters, minecraft does. it's super weird

**Comment by masterbobli** [comment] 2019-06-01 10:13
Maybe we could use some wrong words in lang files so that the game will display the right characters.

**Comment by masterbobli** [comment] 2019-06-04 21:14
Update: Only texts that are not in zh_cn.lang file breaks, which means that the tabs are correctly shown.
![8F33B329-28FF-4BE2-8D47-C2E075A7103A](https://user-images.githubusercontent.com/37212918/58914270-a95ba600-8750-11e9-97d8-190c56853227.png)
![CB584D6B-9535-4998-AB37-A2D0D4103D26](https://user-images.githubusercontent.com/37212918/58914271-a9f43c80-8750-11e9-857c-b2c01f77a7de.png)

**Comment by Angrydog001** [comment] 2019-06-05 05:26
^ Chinese characters are not supported, character conversion is not normal.

**Comment by Angrydog001** [comment] 2019-06-05 05:52
Might Russian has the same problem: https://github.com/Tslat/Advent-Of-Ascension/pull/697

**Comment by Tslat** [comment] 2019-06-05 06:19
Unrelated. The russian translation was bad.

**Comment by Tslat** [comment] 2019-06-05 21:46
Don't close issues unless you're withdrawing them

**Comment by Tslat** [comment] 2019-06-07 01:58
Duplicate of #699

**Closed by Tslat** 2019-06-07 01:58 UTC
Labels: duplicate

**Comment by GTOL** [comment] 2019-10-15 21:13
I also have a similar issue on version 3.1.2.b. My Guide grabled but the characters are different from masterbobli's image.

I think this is due to the windows setting(Language for non-Unicode programs). It will affect the JVM's default encoding. If the locale is set to 'en-XX' (my case), the files will be opened with "Windows 1252" encoding. If the locale is set to 'zh-CN' (his case), the files will be opened with "GB2312" encoding. 
![image](https://user-images.githubusercontent.com/16363483/66868976-ff7b0880-efd0-11e9-9591-da1070e56fa4.png)

After adding "-Dfile.encoding=UTF-8" to JVM parameter, the in-game guide text changed back to normal immediately.

My suggestion is: manually set the encoding to 'UTF-8' for the "inputstreamreader" in AdventGuiTabGuides.java, so that the file will always be opened with 'UTF-8' encoding.

**Comment by Tslat** [comment] 2019-10-15 21:49
Like it says in the linked issue, this has been fixed after 3.1.2.b

https://github.com/Tslat/Advent-Of-Ascension/issues/699#issuecomment-499731485
