### ISSUE TITLE
The game crashes when I tried entering the world.

### ISSUE THREAD

**Issue by marc-shen** [Tslat/Advent-Of-Ascension#2781] opened 2021-07-25 15:36 UTC
[minecraft-exported-logs-2021-07-25T23-31-59.log](https://github.com/Tslat/Advent-Of-Ascension/files/6874122/minecraft-exported-logs-2021-07-25T23-31-59.log)
**Mod Version**
What version of the mod are you on?
3.5.4
**Describe the bug**
The game crashes when I tried entering the world.
**To Reproduce**
Steps to reproduce the behaviour:

**Expected behavior**

**Screenshots**

**Comment by Tslat** [comment] 2021-07-25 18:04
This is fixed in the next version, but for now you can either play the game in java 8 like it was intended, or try downgrading a couple versions until it works

**Closed as completed by Tslat** 2021-07-25 18:04 UTC
Labels: duplicate
