### ISSUE TITLE
Trees´ Sapplings

### ISSUE THREAD

**Issue by Pokesmile-modded** [Tslat/Advent-Of-Ascension#922] opened 2019-10-06 11:31 UTC
I might be a good idea to add Sapplings to the Advent Of Ascension dimensions trees, some woods are pretty fancy but they´re not renovable, it would be possible to create sapplings that need to be planted on these dimensions´ soils. These sapplings would be dropped by these trees´ leaves. You could also add special fruits for every type of tree.

Sorry if I wrote something bad my english isn´t that good I am spanish

**Comment by EatingSilencer** [comment] 2019-10-12 00:19
This is a duplicate of #75.

**Closed** 2020-04-12 02:12 UTC
Labels: duplicate, new feature
