### ISSUE TITLE
Hotkey to turn off night vision goggle's effect

### ISSUE THREAD

**Issue by DiamondWalker** [Tslat/Advent-Of-Ascension#549] opened 2019-04-07 02:59 UTC
Add a hotkey to turn off the night vision goggle's effect. It's annoying to have even if you don't want to use it, and the same goes for taking them off and putting them back on. Pressing some hotkey (maybe V) would turn them off. When turned off, they would not give you the green shader, and the worn texture could change to something like ![nightvision_goggles-1 png](https://user-images.githubusercontent.com/19913710/55677957-8717ea00-58bf-11e9-856d-e363903270aa.png).

**Comment by Tslat** [comment] 2019-04-07 03:12
Effective duplicate of #547

**Closed by Tslat** 2019-04-07 03:12 UTC
Labels: duplicate

**Comment by DiamondWalker** [comment] 2019-04-07 03:22
Not really. It was based on that suggestion, but that one didn't suggest making the screen shader go on or off or changing the texture
