### ISSUE TITLE
incompatible with gregic additions

### ISSUE THREAD

**Issue by kotelkonrad** [Tslat/Advent-Of-Ascension#565] opened 2019-04-15 13:49 UTC
**Mod Version**
What version of the mod are you on?
latest

**To Reproduce**
Steps to reproduce the behaviour:
install gregic additions and AoA

![image](https://user-images.githubusercontent.com/48735640/56137800-dfbd4600-5f95-11e9-91ac-6f273b84f47f.png)
https://paste.dimdev.org/iqiyugecij.mccrash
https://github.com/EmosewaPixel/GregicAdditions/issues/59

**Comment by Tslat** [comment] 2019-04-15 19:02
I need that crash report if you want anything done

**Comment by kotelkonrad** [comment] 2019-04-15 20:10
https://paste.dimdev.org/iqiyugecij.mccrash

**Comment by kotelkonrad** [comment] 2019-04-15 20:11
[latest.log](https://github.com/Tslat/Advent-Of-Ascension/files/3081892/latest.log)

**Comment by Tslat** [comment] 2019-04-15 20:46
Doesn't look to be anything on my side.
I'm closing this for now, if the other dev finds anything that he believes is on my side, someone can let me know

**Closed by Tslat** 2019-04-15 20:46 UTC
Labels: needs further info

**Comment by kotelkonrad** [comment] 2019-04-16 06:26
ok

**Comment by kotelkonrad** [comment] 2019-04-16 12:37
![image](https://user-images.githubusercontent.com/48735640/56209945-0e4e2600-6055-11e9-8f8b-099f9abc2bcc.png)
without gregic additions, and with

**Comment by Tslat** [comment] 2019-04-16 19:04
Yeah looks like on Gregic's side

**Comment by kotelkonrad** [comment] 2019-04-16 19:39
:(

**Comment by Shadows-of-Fire** [comment] 2019-04-17 05:56
This is technically an error caused by an assumption on an automatic recipe processing system.  It would be easier to have you fix it on your end.

Basically, your slabs don't use a 1x3 shaped recipe like they should, they use a 3x3 shaped recipe using empty spaces in the top and bottom slots, which makes it so the automatic processor (which grabs the first ingredient) finds the empty ingredient and errors out on Ingredient#getMatchingStacks.

If you switch your slab recipes to 1x3, not only will your slabs be craftable in the top and bottom rows of the table (mirroring expected behavior established by vanilla), the error will just vanish.

**Comment by Tslat** [comment] 2019-04-17 06:28
Ah well that's already been done for 3.1 anyway, so if that's the problem there then it should be fine once that's out.

However I would still recommend you _don't_ make the assumption, because there is valid reasons for not shrinking the crafting space to fit the recipe
