### ISSUE TITLE
Occult Pickaxe crushes game with secondary ability

### ISSUE THREAD

**Issue by DragWiz** [Tslat/Advent-Of-Ascension#2259] opened 2021-01-09 22:00 UTC
**Mod Version**
3.4.4

**Describe the bug**
Occult Pickaxe cause the game to crash when right clicked. I used it 3-4 times and it always happened.

**To Reproduce**
1. Get an occult picaxe
2. Use the right click to show ores near clumps of ores
3. If it doesn't happen immediatly, move around keeping the right click ability active

**Expected behavior**
Shouldn't crash.
[crashoccultpickaxe.txt](https://github.com/Tslat/Advent-Of-Ascension/files/5791882/crashpt2.txt)

**Comment by Tslat** [comment] 2021-01-16 21:41
This is a tough one because I find it really hard to reproduce.
I have implemented a fix which seems to have fixed it for me, but with it being so inconsistent I can't be 100% sure.

I'm closing this, if it happens again in 3.4.5 or later, re- report it

**Closed as completed by Tslat** 2021-01-16 21:41 UTC
Labels: bug
