### ISSUE TITLE
Loading entity NBT  java.lang.NullPointerException: Loading entity NBT

### ISSUE THREAD

**Issue by Destructuctor** [Tslat/Advent-Of-Ascension#894] opened 2019-09-17 22:34 UTC
Version: Latest for 1.12.2

This bug occurs on loading into a world. I have tried about 3 times to load into a world getting this error every single time. 

I honestly have not seen any reports of this bug, so you may not be able to reproduce, but just try loading into a world.

What did you expect?: For the game to load haha!

FULL Error log: 
https://hasteb.in/ihumiceh.yaml

**Comment by Tslat** [comment] 2019-09-17 22:40
Duplicate of #840

**Closed by Tslat** 2019-09-17 22:40 UTC
Labels: duplicate
