### ISSUE TITLE
Rename halycon beef

### ISSUE THREAD

**Issue by Immortallis1** [Tslat/Advent-Of-Ascension#865] opened 2019-08-31 00:26 UTC
Having creeping cow drop "halycon" beef is kind of stupid. Maybe you could rename "halycon beef" to some generic term (DRPG uses "empowered meat" for instance) that is a catchall for both green cows (hopefully we don't get any more cows).

Figured since loot update is here and all this would be the best time to make such a change

**Comment by Tslat** [comment] 2019-08-31 00:28
Duplicate of #862 
Already resolved

**Closed by Tslat** 2019-08-31 00:28 UTC
Labels: duplicate
